https://medium.com/re-hoop-per-rate/training-a-neural-network-to-fill-out-my-march-madness-bracket-2e5ee562eab1

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv('hotoutliers.csv')


# df = pd.read_csv('hotData.csv')
# df = pd.read_csv('hotoutliers238.csv')
# df = pd.read_csv('features.csv')
# df = pd.read_csv('feature-outliers.csv')

# df = pd.read_csv('pca.csv')

In [3]:
y = df['results']
X = df.drop(columns=['results'])

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.10, random_state=2)

In [4]:
forest_clf=RandomForestClassifier()

In [13]:
cross_val_score(forest_clf, X_train, y_train, cv=3, scoring="accuracy")

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(


array([0.07692308, 0.07692308, 0.05128205])

In [14]:
y_gt0=(y_train<10)
cross_val_score(forest_clf, X_train, y_gt0, cv=3, scoring="accuracy")

array([0.78205128, 0.71794872, 0.71794872])

In [16]:
from sklearn.linear_model import SGDClassifier
sgd_clf=SGDClassifier(random_state=11)
cross_val_score(sgd_clf, X_train, y_gt0, cv=3, scoring="accuracy")

array([0.69230769, 0.70512821, 0.64102564])