In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('wc-qual.csv')

In [3]:
df.head()

team  elo_after_qual  first_qual  wc_results   W  D  L  GF  GA  \
0       France18               6           1           1   7  2  1  18   6   
1       Sweden18              19           0           7   6  1  3  26   9   
2    Portugaul18               4           1          13   9  0  1  32   4   
3  Switzerland18              13           0          14   9  0  1  23   7   
4      Germany18               2           1          23  10  0  0  43   4   

   GD  Pts  
0  12   23  
1  17   19  
2  28   27  
3  16   27  
4  39   30

In [4]:
df.corr()

elo_after_qual  first_qual  wc_results         W         D  \
elo_after_qual        1.000000   -0.322218    0.238045 -0.438525  0.161264   
first_qual           -0.322218    1.000000   -0.088114  0.566969 -0.214683   
wc_results            0.238045   -0.088114    1.000000 -0.373296  0.358404   
W                    -0.438525    0.566969   -0.373296  1.000000 -0.753148   
D                     0.161264   -0.214683    0.358404 -0.753148  1.000000   
L                     0.638340   -0.649365    0.216227 -0.559473  0.026855   
GF                   -0.359219    0.402680   -0.163362  0.752323 -0.525919   
GA                    0.374078   -0.222153    0.362973 -0.230403  0.083398   
GD                   -0.452542    0.446751   -0.265016  0.777967 -0.520000   
Pts                  -0.482316    0.621635   -0.340771  0.978201 -0.600120   

                       L        GF        GA        GD       Pts  
elo_after_qual  0.638340 -0.359219  0.374078 -0.452542 -0.482316  
first_qual     -0.649365  0.402680 -0.222153  0.446751  0.621635  
wc_results      0.216227 -0.163362  0.362973 -0.265016 -0.340771  
W              -0.559473  0.752323 -0.230403  0.777967  0.978201  
D               0.026855 -0.525919  0.083398 -0.520000 -0.600120  
L               1.000000 -0.369270  0.471318 -0.491847 -0.671811  
GF             -0.369270  1.000000 -0.038153  0.951769  0.748767  
GA              0.471318 -0.038153  1.000000 -0.342904 -0.253832  
GD             -0.491847  0.951769 -0.342904  1.000000  0.781819  
Pts            -0.671811  0.748767 -0.253832  0.781819  1.000000

In [5]:
df.shape

(34, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   team            34 non-null     object
 1   elo_after_qual  34 non-null     int64 
 2   first_qual      34 non-null     int64 
 3   wc_results      34 non-null     int64 
 4   W               34 non-null     int64 
 5   D               34 non-null     int64 
 6   L               34 non-null     int64 
 7   GF              34 non-null     int64 
 8   GA              34 non-null     int64 
 9   GD              34 non-null     int64 
 10  Pts             34 non-null     int64 
dtypes: int64(10), object(1)
memory usage: 3.0+ KB


In [7]:
df = df.drop(columns=['team'])

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
y = df['wc_results']

In [10]:
X = df.drop(columns=['wc_results'])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
from sklearn import linear_model
reg = linear_model.LinearRegression()


In [13]:
reg.fit(X_train, y_train)

LinearRegression()

In [14]:
reg.coef_

array([ 0.08582096,  0.35324903, -1.18297838,  4.92519968,  1.74800243,
        0.18879194,  0.61061827, -0.42182633,  1.37626455])

In [15]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.5)

In [16]:
reg.fit(X_train, y_train)

Ridge(alpha=0.5)

In [17]:
reg.coef_

array([ 0.09346791,  0.19546318, -1.13659273,  4.6376574 ,  1.25201447,
        0.20535662,  0.63394303, -0.42858641,  1.22787919])

In [18]:
reg.intercept_

-19.430382509178997

In [20]:
reg.predict(X_test)

array([ 7.74419486,  8.02773003, 11.86169106,  4.09973427, 12.69624013,
       12.84852489, 18.13243116, 14.7869166 , 20.65835829,  4.9857406 ,
       14.49533016,  1.07370188])

In [21]:
y_test

15     3
19    23
27    23
26    13
8      4
24     3
21    24
12     6
32    11
9     10
0      1
4     23
Name: wc_results, dtype: int64